micronaut.server.port=8081
datasources.default.db-type=postgres
datasources.default.dialect=POSTGRES
micronaut.application.name=portfolio
datasources.default.schema-generate=validate
datasources.default.driver-class-name=org.postgresql.Driver
datasources.default.jdbc-url=jdbc:postgresql://localhost:5432/portfolio_db
datasources.default.username=portfolio_user
datasources.default.password=sup3rS3cr3tP4ssw0rd
flyway.datasources.default.enabled=true