micronaut.server.port=8080
micronaut.application.name=operations
# Database
datasources.default.dialect=POSTGRES
datasources.default.driver-class-name=org.postgresql.Driver
datasources.default.jdbc-url=jdbc:postgresql://postgres_db:5432/operations_db
datasources.default.password=sup3rS3cr3tP4ssw0rd
datasources.default.username=operations_user
datasources.default.schema-generate=validate
flyway.datasources.default.enabled=true
# Kafka
kafka.bootstrap.servers=broker:9092